version: '2'
services:
  dbserver:
    image: mysql:5.7
    hostname: dbserver
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=wordlearning
  reverseproxy:
    image: nginx
    hostname: reverseproxy
    ports:
     - 8080:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - webapp
  webapp:
    image: python:3.6.1
    command: /app/run.sh
    hostname: webapp
    volumes:
      - ./project:/app
      - ./requirements.txt:/requirements.txt
    links:
      - dbserver
  cron:
    image: alpine
    command: sh -c "echo '* * * * * wget http://webapp:8080/parse/weblio >/dev/null 2>&1' > /var/spool/cron/crontabs/root; crond -f"