# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('date', models.DateField(verbose_name='Date')),
                ('title', models.TextField(verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True, verbose_name='Word')),
                ('status', models.CharField(choices=[('master', 'master'), ('studying', 'studying'), ('not started', 'not started'), ('ignore', 'ignore')], max_length=16, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='WordsInArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(verbose_name='Article ID')),
                ('word', models.CharField(max_length=255, unique=True, verbose_name='Word')),
                ('count', models.IntegerField(verbose_name='Count')),
            ],
        ),
    ]
