# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
        migrations.RenameModel(
            old_name='WordsInArticle',
            new_name='WordCount',
        ),
    ]
