# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170508_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcount',
            name='word',
            field=models.CharField(max_length=255, verbose_name='Word'),
        ),
    ]
