# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170508_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcount',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_word', to='app.Word'),
        ),
    ]
