# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170508_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='domain',
            field=models.CharField(default='dummy', max_length=255, unique=True, verbose_name='Domain'),
            preserve_default=False,
        ),
    ]
