# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_article_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='domain',
            field=models.CharField(max_length=255, verbose_name='Domain'),
        ),
    ]
