# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170509_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='status',
            field=models.CharField(choices=[('master', 'success'), ('studying', 'info'), ('not started', 'danger'), ('ignore', 'default')], max_length=16, verbose_name='Status'),
        ),
    ]
